@TokenParserAPI_HostAddress = http://localhost:5228

### Alive
get {{TokenParserAPI_HostAddress}}/alive
Accept: application/json

###
### Parse today's date token
get {{TokenParserAPI_HostAddress}}/parse-date-token?token=%5BTODAY%5D
Accept: application/json

###
### Parse adjusted date token
get {{TokenParserAPI_HostAddress}}/parse-date-token?token=%5BTODAY%2B1YEAR-2MONTH%5D
Accept: application/json

###
### Parse dynamic string token
get {{TokenParserAPI_HostAddress}}/parse-dynamic-string-token?token=%5BALPHA-NUMERIC-PUNCTUATION-10-LINES-2%5D
Accept: application/json
