// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TokenParserTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TokenDynamicStringParser String Generation")]
    [NUnit.Framework.CategoryAttribute("utiltests")]
    public partial class TokenDynamicStringParserStringGenerationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "utiltests"};
        
#line 1 "TokenDynamicStringParserUtil.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "TokenDynamicStringParser String Generation", "    As a developer,\r\n    I want to validate the correct functionality of the Toke" +
                    "nDynamicStringParser class,\r\n    So that it can generate the expected strings ba" +
                    "sed on different token formats, including multi-line strings.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generate string based on token input")]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-5]", "5", "ALPHA", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[NUMERIC-5]", "5", "NUMERIC", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-NUMERIC-10]", "10", "ALPHA_NUMERIC", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[NUMERIC-ALPHA-20]", "20", "ALPHA_NUMERIC", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-NUMERIC-PUNCTUATION-12]", "12", "ALPHA_NUMERIC_PUNCTUATION", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[SPECIAL-6]", "6", "SPECIAL", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-PUNCTUATION-8]", "8", "ALPHA_PUNCTUATION", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[PUNCTUATION-ALPHA-123]", "123", "ALPHA_PUNCTUATION", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-NUMERIC-SPECIAL-15]", "15", "ALPHA_NUMERIC_SPECIAL", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-5-LINES-3]", "15", "ALPHA", "3", null)]
        [NUnit.Framework.TestCaseAttribute("[NUMERIC-4-LINES-4]", "16", "NUMERIC", "4", null)]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-NUMERIC-5-LINES-2]", "10", "ALPHA_NUMERIC", "2", null)]
        [NUnit.Framework.TestCaseAttribute("[SPECIAL-ALL]", "24", "SPECIAL", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[PUNCTUATION-ALL]", "6", "PUNCTUATION", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[SPECIAL-PUNCTUATION-ALL]", "30", "SPECIAL_PUNCTUATION", "1", null)]
        public void GenerateStringBasedOnTokenInput(string token, string length, string characterSet, string lines, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("token", token);
            argumentsOfScenario.Add("length", length);
            argumentsOfScenario.Add("characterSet", characterSet);
            argumentsOfScenario.Add("lines", lines);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate string based on token input", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
        testRunner.Given(string.Format("a token \"{0}\"", token), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 10
        testRunner.When("I parse and generate the string", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
        testRunner.Then(string.Format("the generated string should have a length of {0}", length), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 12
        testRunner.And(string.Format("the generated string should match the character set \"{0}\"", characterSet), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
        testRunner.And(string.Format("the generated string should have {0} lines", lines), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Invalid tokens raise descriptive errors")]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-5-LINES-0]", "Invalid line count in token", null)]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-5-LINES-XYZ]", "Invalid string token format", null)]
        [NUnit.Framework.TestCaseAttribute("[ALPHA-0]", "Invalid string token format", null)]
        public void InvalidTokensRaiseDescriptiveErrors(string token, string message, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("token", token);
            argumentsOfScenario.Add("message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid tokens raise descriptive errors", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 34
        testRunner.Given(string.Format("a token \"{0}\"", token), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 35
        testRunner.When("I parse and generate the string", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
        testRunner.Then(string.Format("a dynamic string parser error should be thrown with message \"{0}\"", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
