// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TokenParserTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Parsing dates from token format strings using TokenDateParser")]
    [NUnit.Framework.CategoryAttribute("utiltests")]
    public partial class ParsingDatesFromTokenFormatStringsUsingTokenDateParserFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "utiltests"};
        
#line 1 "TokenDateParserUtil.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Parsing dates from token format strings using TokenDateParser", "    In order to accurately compute dates from token format strings\r\n    As a user" +
                    " of the TokenDateParser class\r\n    I want to be able to input a variety of token" +
                    " strings and get the correct date output", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsing relative date tokens - [STARTDATE][+ve/-ve][DATEPART][+ve/-ve][DATEPART][" +
            "+ve/-ve][DATEPART]")]
        [NUnit.Framework.TestCaseAttribute("[TODAY]", "0", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("[TOMORROW]", "0", "0", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[YESTERDAY]", "0", "0", "-1", null)]
        [NUnit.Framework.TestCaseAttribute("[TODAY-2YEAR-4MONTH]", "-2", "-4", "0", null)]
        [NUnit.Framework.TestCaseAttribute("[TODAY-1YEAR-1MONTH]", "-1", "-1", "0", null)]
        [NUnit.Framework.TestCaseAttribute("[TODAY-1YEAR-2MONTH-3DAY]", "-1", "-2", "-3", null)]
        [NUnit.Framework.TestCaseAttribute("[TODAY+1YEAR-1MONTH+1DAY]", "1", "-1", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[TODAY+2YEAR]", "2", "0", "0", null)]
        [NUnit.Framework.TestCaseAttribute("[TODAY+5MONTH]", "0", "5", "0", null)]
        [NUnit.Framework.TestCaseAttribute("[TOMORROW+5MONTH]", "0", "5", "1", null)]
        [NUnit.Framework.TestCaseAttribute("[YESTERDAY+5MONTH-1YEAR]", "-1", "5", "-1", null)]
        public void ParsingRelativeDateTokens_STARTDATEVe_VeDATEPARTVe_VeDATEPARTVe_VeDATEPART(string token, string years, string months, string days, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("token", token);
            argumentsOfScenario.Add("years", years);
            argumentsOfScenario.Add("months", months);
            argumentsOfScenario.Add("days", days);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Parsing relative date tokens - [STARTDATE][+ve/-ve][DATEPART][+ve/-ve][DATEPART][" +
                    "+ve/-ve][DATEPART]", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
        testRunner.Given(string.Format("A date token \"{0}\"", token), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 10
        testRunner.When("I parse the token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 11
        testRunner.Then(string.Format("the result should equal today plus {0} years {1} months {2} days", years, months, days), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Handling null or invalid token input - [STARTDATE][+ve/-ve][DATEPART][+ve/-ve][DA" +
            "TEPART][+ve/-ve][DATEPART]")]
        public void HandlingNullOrInvalidTokenInput_STARTDATEVe_VeDATEPARTVe_VeDATEPARTVe_VeDATEPART()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Handling null or invalid token input - [STARTDATE][+ve/-ve][DATEPART][+ve/-ve][DA" +
                    "TEPART][+ve/-ve][DATEPART]", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 28
        testRunner.Given("An invalid date range string \"INVALID-TOKEN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 29
        testRunner.When("I parse the token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
        testRunner.Then("an error should be thrown with message \"Invalid string token format\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsing several instances of a second format of date string tokens - [MONTHENDSTA" +
            "RT][MONTH][YEAR]")]
        [NUnit.Framework.TestCaseAttribute("[START-JANUARY-2024]", "2024-01-01", null)]
        [NUnit.Framework.TestCaseAttribute("[END-FEBRUARY-2024]", "2024-02-29", null)]
        [NUnit.Framework.TestCaseAttribute("[END-FEBRUARY-2022]", "2022-02-28", null)]
        [NUnit.Framework.TestCaseAttribute("[END-OCTOBER-2020]", "2020-10-31", null)]
        [NUnit.Framework.TestCaseAttribute("[START-DECEMBER-2000]", "2000-12-01", null)]
        [NUnit.Framework.TestCaseAttribute("[END-JUNE-2025]", "2025-06-30", null)]
        public void ParsingSeveralInstancesOfASecondFormatOfDateStringTokens_MONTHENDSTARTMONTHYEAR(string dateStringToken, string expectedDate, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("dateStringToken", dateStringToken);
            argumentsOfScenario.Add("expectedDate", expectedDate);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Parsing several instances of a second format of date string tokens - [MONTHENDSTA" +
                    "RT][MONTH][YEAR]", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
        testRunner.Given(string.Format("A date string \"{0}\"", dateStringToken), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 34
        testRunner.When("I parse the date string token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 35
        testRunner.Then(string.Format("the result should be \"{0}\"", expectedDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parsing several instances of date range token strings - [MONTHENDSTART][MONTH][YE" +
            "AR]<->[MONTHENDSTART][MONTH][YEAR]")]
        [NUnit.Framework.TestCaseAttribute("[START-JANUARY-2024<->END-FEBRUARY-2024]", "2024-01-01", "2024-02-29", null)]
        [NUnit.Framework.TestCaseAttribute("[END-OCTOBER-2020<->END-FEBRUARY-2022]", "2020-10-31", "2022-02-28", null)]
        [NUnit.Framework.TestCaseAttribute("[START-DECEMBER-2021<->END-JUNE-2025]", "2021-12-01", "2025-06-30", null)]
        [NUnit.Framework.TestCaseAttribute("[START-JULY-2021<->START-MARCH-2023]", "2021-07-01", "2023-03-01", null)]
        public void ParsingSeveralInstancesOfDateRangeTokenStrings_MONTHENDSTARTMONTHYEAR_MONTHENDSTARTMONTHYEAR(string dateRangeTokenString, string startDate, string endDate, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("dateRangeTokenString", dateRangeTokenString);
            argumentsOfScenario.Add("StartDate", startDate);
            argumentsOfScenario.Add("EndDate", endDate);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Parsing several instances of date range token strings - [MONTHENDSTART][MONTH][YE" +
                    "AR]<->[MONTHENDSTART][MONTH][YEAR]", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 47
        testRunner.Given(string.Format("A date range string \"{0}\"", dateRangeTokenString), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 48
        testRunner.When("I parse the date range string", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 49
        testRunner.Then(string.Format("the start date should be \"{0}\" and the end date should be \"{1}\"", startDate, endDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
