"""Canonical keys for actor memory."""


class MemoryKeys:
    LAST_RESPONSE = "LAST_RESPONSE"
    LAST_UTIL_RESULT = "LAST_UTIL_RESULT"
    LAST_PARSED_DATE = "LAST_PARSED_DATE"
    SECONDARY_PARSED_DATE = "SECONDARY_PARSED_DATE"
    LAST_PARSED_RANGE = "LAST_PARSED_RANGE"
    LAST_PARSE_ERROR = "LAST_PARSE_ERROR"
    LAST_GENERATED_STRING = "LAST_GENERATED_STRING"
